//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchTags_SmartAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fraccionamiento
    {
        public int IdFraccionamiento { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string Domicilio { get; set; }
        public string IP { get; set; }
        public string ServerSql { get; set; }
        public string PuertoSql { get; set; }
        public string UserSql { get; set; }
        public string PswSql { get; set; }
        public string MacAdress { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
